modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="trading_machine"
version="0.1.0"
displayName="Trading Machine"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Qikahome, MCreator"
description="A Method to Trade between Players"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.trading_machine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration